[package]
name = "sdf2mesh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
euclid = "0.22.9"
wgpu = "0.18.0"
nalgebra = "0.32.3"
log = "0.4"
futures-intrusive = "0.5"
png = "0.17.10"
env_logger = "0.10"
pollster = "0.3"
encase = "0.6"
bytemuck = "1.14.0"

[[bin]]
name="sdf2mesh"

