[package]
name = "sdf2mesh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.14.0"
clap = { version = "4.1", features = ["derive","cargo"] }
common_macros = "0.1.1"
encase = "0.6"
env_logger = "0.10"
euclid = "0.22.9"
futures-intrusive = "0.5"
lazy_static = "1.4.0"
log = "0.4"
nalgebra = "0.32.3"
png = "0.17.10"
pollster = "0.3"
wgpu = "0.18.0"

[[bin]]
name="sdf2mesh"

